#!/bin/bash
#
# Installs the helper app for the "Menubar for Symfony" GNOME Shell extension.
#
# Nothing is compiled and nothing is downloaded: the helper is plain JavaScript
# run by /usr/bin/gjs, which every system running GNOME Shell already has. No
# root privileges are needed — everything lands under your home directory.
#
# Works both from a release tarball and from a git checkout that has been built
# with `npm run build`.

set -euo pipefail

BUNDLE_NAME="symfony-menubar-daemon.js"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/symfony-menubar-daemon"
BIN_DIR="$HOME/.local/bin"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/symfony-menubar"
WRAPPER="$BIN_DIR/symfony-menubar-daemon"

# A release tarball ships the bundle next to this script; a git checkout has it
# under dist/ after a build.
SOURCE=""
for candidate in "$HERE/$BUNDLE_NAME" "$HERE/dist/$BUNDLE_NAME"; do
    if [ -f "$candidate" ]; then
        SOURCE="$candidate"
        break
    fi
done

if [ -z "$SOURCE" ]; then
    echo "Error: $BUNDLE_NAME not found next to this script or in ./dist." >&2
    echo "If this is a git checkout, run 'npm install && npm run build' first." >&2
    exit 1
fi

if ! command -v gjs >/dev/null; then
    echo "Error: gjs was not found on PATH." >&2
    echo "It ships with GNOME Shell; install the 'gjs' package if it is missing." >&2
    exit 1
fi

GJS="$(command -v gjs)"

echo "Installing the helper app"

mkdir -p "$DATA_DIR" "$BIN_DIR" "$CONFIG_DIR"
install -m 644 "$SOURCE" "$DATA_DIR/$BUNDLE_NAME"
echo "  helper      $DATA_DIR/$BUNDLE_NAME"

cat > "$WRAPPER" <<EOF
#!/bin/sh
# Generated by install.sh
exec "$GJS" -m "$DATA_DIR/$BUNDLE_NAME" "\$@"
EOF
chmod 755 "$WRAPPER"
echo "  launcher    $WRAPPER"

# Registers the helper for D-Bus activation, so the extension never starts a
# process itself: the session bus starts it on the first method call.
"$WRAPPER" --install-service

# Before version 1.3 actions.json lived inside the extension directory, which
# GNOME replaces wholesale on every extension update.
LEGACY_ACTIONS="$HOME/.local/share/gnome-shell/extensions/menubar-for-symfony@tito10047.github.com/actions.json"
if [ -f "$LEGACY_ACTIONS" ] && [ ! -f "$CONFIG_DIR/actions.json" ]; then
    cp "$LEGACY_ACTIONS" "$CONFIG_DIR/actions.json"
    echo "  actions     migrated to $CONFIG_DIR/actions.json"
fi

echo
echo "Done. Custom actions belong in $CONFIG_DIR/actions.json"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "Note: $BIN_DIR is not on your PATH. D-Bus activation works regardless;"
       echo "      add it if you want to run 'symfony-menubar-daemon' by hand." ;;
esac

if gdbus call --session --dest org.freedesktop.DBus --object-path /org/freedesktop/DBus \
        --method org.freedesktop.DBus.GetNameOwner com.github.tito10047.SymfonyMenubar >/dev/null 2>&1; then
    echo "Note: an older helper is still running. Run 'symfony-menubar-daemon --replace'"
    echo "      or toggle the extension off and on to pick up this version."
fi
